# Site settings
title: Numero, knjigovodstveni obrt
email: knjigovodstvo.numero@gmail.com
url: https://numero.hr
description: "Numero, knjigovodstveni obrt. Knjigovodstvene usluge obrtima, slobodnim zanimanjima, poljoprivrednicima, mikro poduzetnicima i neprofitnim organizacijama. Porezno i financijsko savjetovanje i planiranje."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#AD1D4B'

# Footer settings
footer: Numero

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: telegram
    url: https://t.me/blakadder
  - title: facebook
    url: https://www.facebook.com/Numero-knjigovodstveni-obrt-i-poslovno-savjetovanje-126330890723748/
  - title: viber
    url: viber://chat?number=38598712881

# Build settings
markdown: kramdown
permalink: pretty
remote_theme: jeromelachaud/grayscale-theme
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
